// Mocks generated by Mockito 5.0.15 from annotations
// in podcast_app/test/application/create_channel_test.dart/create_channel_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:podcast_app/data_provider/Ichannel_provider.dart' as _i2;
import 'package:podcast_app/models/channel/Channel.dart' as _i3;
import 'package:podcast_app/repository/ChannelRepository.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeIChannelProvider_0 extends _i1.Fake implements _i2.IChannelProvider {
}

class _FakeChannel_1 extends _i1.Fake implements _i3.Channel {}

/// A class which mocks [ChannelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannelRepository extends _i1.Mock implements _i4.ChannelRepository {
  MockChannelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IChannelProvider get channelProvider =>
      (super.noSuchMethod(Invocation.getter(#channelProvider),
          returnValue: _FakeIChannelProvider_0()) as _i2.IChannelProvider);
  @override
  _i5.Future<_i3.Channel> getChannel(String? channelId) =>
      (super.noSuchMethod(Invocation.method(#getChannel, [channelId]),
              returnValue: Future<_i3.Channel>.value(_FakeChannel_1()))
          as _i5.Future<_i3.Channel>);
  @override
  _i5.Future<bool> isSubscribed(String? userId, String? channelId) =>
      (super.noSuchMethod(Invocation.method(#isSubscribed, [userId, channelId]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<bool> setSubscription(
          String? userId, String? channelId, bool? subscriptionStatus) =>
      (super.noSuchMethod(
          Invocation.method(
              #setSubscription, [userId, channelId, subscriptionStatus]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<_i3.Channel?> createChannel(
          {String? Name, String? Description, dynamic ImageURL}) =>
      (super.noSuchMethod(
              Invocation.method(#createChannel, [], {
                #Name: Name,
                #Description: Description,
                #ImageURL: ImageURL
              }),
              returnValue: Future<_i3.Channel?>.value())
          as _i5.Future<_i3.Channel?>);
  @override
  _i5.Future<_i3.Channel?> editChannel(
          {String? Name,
          String? Description,
          dynamic ImageURL,
          String? ChannelID}) =>
      (super.noSuchMethod(
              Invocation.method(#editChannel, [], {
                #Name: Name,
                #Description: Description,
                #ImageURL: ImageURL,
                #ChannelID: ChannelID
              }),
              returnValue: Future<_i3.Channel?>.value())
          as _i5.Future<_i3.Channel?>);
  @override
  String toString() => super.toString();
}
